1D inverse problems showcase from hackathon
TomographicImaging/CIL-User-Showcase pull request #3
Opened 2023-04-13 13:40 UTC by billlion

## Describe your contribution

## Checklist when you are ready to request a review

- [x] I have performed a self-review of my code
- [x] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [x] I have added a description of my contribution(s) to the top of my file(s)
- [x] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [x] I have added the CIL version I ran with near the top of my file(s)
- [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [x] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [x] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [x] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

2023-04-14 17:02 UTC, lauramurgatroyd requested changes
Hi Bill,

Thanks for the contribution!

Just some initial comments on the format of the notebook.

2023-04-21 10:51 UTC, jakobsj requested changes
Hi @billlion many thanks for adding this nice notebook of a 1D case.

In addition to the comments by @lauramurgatroyd relating to general tidying up, removing empty cells, old comments and unused code etc., I have the following suggestions/questions on the content/flow of the notebook:

- Just below the notebook title, please add your name and institution for author.
- The loglog plot of the singular value has a steep jump at the end. Is this to be expected? Is the problem numerically rank-deficient?
- Just before that, the comment "expected for an operator that approximates the inverse of two derivatives" is not quite clear to me.  Could you perhaps explain the deriv2 problem a bit more, that would add helpful context for those who may not know Regularization Tools and/or the deriv2 problem, and then elaborate on what is meant by "two derivatives".
- Please provide the notebook with outputs run once in order from a fresh kernel.
- The result of the first tikhonov (using lstsq and numpy) looks quite different from the true x. Is this expected? Is there a bug? Please add some commentary to the notebook to explain what we observe and how that fits with the theory.
- When the notebook turns to CIL types, the notebook has limited commentary. Could you add some more to guide the reader? For example, explain why we run CGLS, what we see from the CGLS solution (which is very wavy, is that expected?)
- After the first part on CIL, the notebook returns to look at numpy A and bn? What is the point there? Could this be moved up to before the CIL stuff starts to have all the numpy stuff together? Also the xlq appears to plotted twice, did you mean to make a comparison with something else?
- The last part with Tikhonov in CIL is nice but lacks explanation. Would it make sense to compare the CIL Tikhonov with the numpy tikhonov and not just the true x?

Once again, thank you for adding this example. With a bit of tidying up, restructuring, checking the deriv2 implementation and additional commentary, it will make a very nice notebook showcasing how easy it is to set up a 1D problem in CIL, so that users can explore classic 1D inverse problems and at the same time be set up for larger and higher-dimensional inverse problems.

2023-07-25 15:19 UTC, MargaretDuff commented
I created a new pull request to https://github.com/billlion/CIL-User-Showcase that dealt with some of the issues

2023-07-28 15:05 UTC, MargaretDuff commented on 1DIP/deriv2_cgls.ipynb
> +    "This notebook was developed as part of the CCPi CIL Hackathon https://ccpi.ac.uk/events/byod-cil-hackathon/ in March 2023 in Cambridge as part of the Rich Nonlinear Tomography programme at the I
Fixed

2023-07-28 15:05 UTC, MargaretDuff commented on 1DIP/deriv2_cgls.ipynb
> +    "import numpy as np\n",
Fixed

2023-07-28 15:05 UTC, MargaretDuff commented on 1DIP/deriv2_cgls.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAiwAAAGdCAYAAAAxCSikAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAABbY0lEQVR4nO3
Fixed

2023-07-28 15:06 UTC, MargaretDuff commented
Reviewed by Jakob and the pull request on https://github.com/billlion/CIL-User-Showcase  should be ready to merge

2023-08-04 06:05 UTC, jakobsj approved these changes
I am happy to see this updated version merged, thanks all!

2023-08-04 06:07 UTC, jakobsj commented
@lauramurgatroyd Merging awaits resolving of the changes you requested - could you take a look and see if you are happy with merging this version please?

2023-08-07 08:47 UTC, lauramurgatroyd requested changes
Sorry I just noticed a couple of extra things when I came back to resolve comment threads

2023-08-07 08:47 UTC, lauramurgatroyd commented on 003_1D_integral_inverse_problem/__pycache__/deriv2.cpython-310.pyc
Is this file needed?

2023-08-07 08:47 UTC, lauramurgatroyd commented on 003_1D_integral_inverse_problem/deriv2.py
> +import numpy as np
I think we should have a license header on this file too

2023-08-07 08:47 UTC, lauramurgatroyd commented on 003_1D_integral_inverse_problem/deriv2_cgls.ipynb
> +    "#   Edited by:  Margaret DUff (STFC - UKRI)"
```suggestion
    "#   Edited by:  Margaret Duff (STFC - UKRI)"
```

2023-08-07 09:25 UTC, MargaretDuff commented
Thanks @lauramurgatroyd! @billlion I created a new pull request to deal with Laura's comments - if you could approve that would be great!

2023-08-08 07:45 UTC, MargaretDuff commented
Thanks @billlion! @lauramurgatroyd - could you check you are happy and merge if so?

2023-08-08 07:58 UTC, lauramurgatroyd approved these changes

2023-08-08 08:02 UTC, merged